### ISSUE TITLE
[IAM] 생성요청

### ISSUE THREAD

**Issue by dataminegames** [UpstageAI/aws-help-desk#12]
### 사용할 서비스
- EC2, VPC

### 권한
- ReadAndWrite (Full Access)

### 사용자명 및 Email, 사 내/외 여부
- BoyoonJang, boyoon.jang@upstage.ai, 사내

### 계정명, 초기비밀번호
- boyoon.jang // upupup!!

### 예상 사용 기간
- 퇴사까지

### 간단한 사용 용도
- 고객사별 모델 평가 지표 모니터링을 위한 내부용 대시보드를 배포할 예정입니다.

#### Document
https://www.notion.so/AWS-53a34993dc5749f9b1e6368634168212

**Comment by JunYeopLee** [comment]
안녕하세요! 생성해서 메일드렸습니다. 감사합니다.
