### ISSUE TITLE
[IAM] 생성요청

### ISSUE THREAD

**Issue by aporia3517** [UpstageAI/aws-help-desk#13]
### 사용할 서비스
- ex) S3, EC2, Sagemaker, ECR, Lambda, Redshift

### 권한
- ex) ReadAndWrite (Full Access)

### 사용자명 및 Email, 사 내/외 여부
- ex) wonsunglee, wonsung.lee@upstage.ai, 사내

### 계정명, 초기비밀번호
- ex) wonsung.lee // upupup

### 예상 사용 기간
- ex) 퇴사 시
 
### 간단한 사용 용도
- ex) RecSys 서빙을 위한 데이터파이프라인 작성

#### Document
https://www.notion.so/AWS-53a34993dc5749f9b1e6368634168212

**Comment by JunYeopLee** [comment]
생성해드렸습니다!
