### ISSUE TITLE
[IAM] AWS 계정 및 IAM User 생성요청

### ISSUE THREAD

**Issue by minchang** [UpstageAI/aws-help-desk#14]
### 사용/생성할 AWS Account
- Account 이름: Personalize-Zamface-Dev
- Account 이메일: upstage-personalize+zamface+dev@upstage.ai

### 사용할 서비스
- ex) 전체, Administrator 권한 필요. 

### 권한
- ex) ReadAndWrite (Full Access)

### 사용자명 및 Email, 사 내/외 여부
- ex) zamface-admin,  upstage-personalize+zamface+dev@upstage.ai, 사내

### 계정명, 초기비밀번호
- ex) zamface-admin, 자동 생성 가능하시면 자동 생성으로 부탁 드립니다. 

### 예상 사용 기간
- ex) 1년

### 간단한 사용 용도
- ex) Zamface 전달용 인프라스트럭처 구축 및 테스트 작업.

#### Document
https://www.notion.so/AWS-53a34993dc5749f9b1e6368634168212

**Comment by JunYeopLee** [comment]
생성 되었습니다!
![image](https://user-images.githubusercontent.com/12492404/135457877-8a169468-2416-4af4-9d53-7583dd47af50.png)
