### ISSUE TITLE
[IAM] AWS 계정 생성 요청

### ISSUE THREAD

**Issue by yongjincho** [UpstageAI/aws-help-desk#15]
### 계정 정보
- account 이름: aiplatform-dev
- account 이메일: aiplatform+dev@upstage.ai

### 사용할 서비스
- ex) S3

### 권한
- ex) ReadOnly or ReadAndWrite (Full Access)

### 사용자명 및 Email, 사 내/외 여부
- ex) JunyeopLee, junyeop.lee@upstage.ai, 사내

### 계정명, 초기비밀번호
- ex) junyeop.lee // upupup

### 예상 사용 기간
- ex) 1년

### 간단한 사용 용도
- ex) 내부 모델파일 저장 용도로 사용합니다.

#### Document
https://www.notion.so/AWS-53a34993dc5749f9b1e6368634168212

**Comment by JunYeopLee** [comment]
생성되었습니다! 메일 확인 부탁드립니다~!
