### ISSUE TITLE
[IAM] 생성요청

### ISSUE THREAD

**Issue by jaeholee2212** [UpstageAI/aws-help-desk#16]
### 사용할 서비스
- S3
- EC2
- ECR
- Route53
- RDS
- Lambda
- Redshift

### 권한
ReadAndWrite (Full Access)

### 사용자명 및 Email, 사 내/외 여부
JaehoLee, jaeholee@upstage.ai, 사내

### 계정명, 초기비밀번호
jaeholee // upupup

### 예상 사용 기간
1년

### 간단한 사용 용도
- Pack개발을 위해서 필요한 리소스들 사용

#### Document
https://www.notion.so/AWS-53a34993dc5749f9b1e6368634168212

**Comment by JunYeopLee** [comment]
생성해드렸습니다!!

**Comment by jaeholee2212** [comment]
감사합니다. 로그인 잘 하였습니다!!!
