### ISSUE TITLE
[IAM] 생성요청

### ISSUE THREAD

**Issue by yongjincho** [UpstageAI/aws-help-desk#6]
### 사용할 서비스
- VPC, EKS, ECR, S3, EC2

### 권한
- ReadAndWrite (Full Access)

### 사용자명 및 Email, 사 내/외 여부
- Yongjin Cho, yongjin.cho@upstage.ai, 사내

### 계정명, 초기비밀번호
- yongjin, upstage!

### 예상 사용 기간
- 계속(?)

### 간단한 사용 용도
- GPU 클라우드 인프라 구성

#### Document
https://www.notion.so/AWS-53a34993dc5749f9b1e6368634168212

**Comment by JunYeopLee** [comment]
@yongjincho 용진님 요청하신 생성해드렸습니다. 초기비번이 aws 계정 정책에 안맞아서 자동생성으로 보내드렸습니다. 최초 계정 접속시 비번 재설정 요청가게 되어 있습니다.
