### ISSUE TITLE
[IAM] 생성요청

### ISSUE THREAD

**Issue by JuHyung-Son** [UpstageAI/aws-help-desk#7]
### 사용할 서비스
- VPC, EKS, ECR, S3, EC2
### 권한
- ReadAndWrite (Full Access)
### 사용자명 및 Email, 사 내/외 여부
- JuHyung Son, juhyung@upstage.ai, 사내
### 계정명, 초기비밀번호
juhyung, zorba1!
### 예상 사용 기간
- 퇴사때까지
### 간단한 사용 용도
- mlops 시스템 구성
### Document
https://www.notion.so/AWS-53a34993dc5749f9b1e6368634168212

**Comment by JunYeopLee** [comment]
사용자명에 공백포함이 불가해서 JuHyungSon 으로 생성드렸습니다. 이메일 발송될 예정입니다.
초기비번의 경우 정책에 맞지 않아서 자동생성으로 전송드리고, 최초 로그인시에 수정요청으로 설정했습니다.

로그인 + 권한 확인되시면 issue close 해주세요!

**Comment by JuHyung-Son** [comment]
AmazonEC2ContainerRegistryFullAccess

권한이 추가로 필요할 거 같아요.
github actions에서 ` arn:aws:iam::***:user/JuHyungSon is not authorized to perform: ecr:GetAuthorizationToken on resource: *` 가 뜨는데 저 권한인거 같아요

**Comment by JunYeopLee** [comment]
@JuHyung-Son 아 public 만 열어드렸네요. 권한 다시 편집해드렸는데 한 번 확인해보시겠어요~?!

**Comment by JuHyung-Son** [comment]
@JunYeopLee 

lambda, sqs 권한 추가로 요청드립니다~!

**Comment by JunYeopLee** [comment]
네 권한 넣어드렸습니다!

**Comment by JuHyung-Son** [comment]
@JunYeopLee 
sqs 쓰려면 sns 권한도 있어야 하나보네요..
SNS 권한도 추가 요청드려요

**Comment by JunYeopLee** [comment]
cloudwatch FA 로 넣어드렸습니다. 감사합니다.
